# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrtaints_HDMI.xdc

# XDC: new/dummyfile.xdc

# Block Designs: bd/block_diagram_HDMI/block_diagram_HDMI.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_HDMI || ORIG_REF_NAME==block_diagram_HDMI} -quiet] -quiet

# IP: bd/block_diagram_HDMI/ip/block_diagram_HDMI_PixelOutput_0_0/block_diagram_HDMI_PixelOutput_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_HDMI_PixelOutput_0_0 || ORIG_REF_NAME==block_diagram_HDMI_PixelOutput_0_0} -quiet] -quiet

# IP: bd/block_diagram_HDMI/ip/block_diagram_HDMI_HDMI_TMDS_0_0/block_diagram_HDMI_HDMI_TMDS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_HDMI_HDMI_TMDS_0_0 || ORIG_REF_NAME==block_diagram_HDMI_HDMI_TMDS_0_0} -quiet] -quiet

# IP: bd/block_diagram_HDMI/ip/block_diagram_HDMI_ClockGenerator_0_0/block_diagram_HDMI_ClockGenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_HDMI_ClockGenerator_0_0 || ORIG_REF_NAME==block_diagram_HDMI_ClockGenerator_0_0} -quiet] -quiet

# XDC: bd/block_diagram_HDMI/block_diagram_HDMI_ooc.xdc
