# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/vsoab/Documents/GitHub/HDMI_project/HDMI/HDMI_Main/HDMI_Main.srcs/sources_1/bd/block_diagram_HDMI/ip/block_diagram_HDMI_clk_wiz_0_0/block_diagram_HDMI_clk_wiz_0_0.xci
# IP: The module: 'block_diagram_HDMI_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vsoab/Documents/GitHub/HDMI_project/HDMI/HDMI_Main/HDMI_Main.srcs/sources_1/bd/block_diagram_HDMI/ip/block_diagram_HDMI_clk_wiz_0_0/block_diagram_HDMI_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_diagram_HDMI_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/vsoab/Documents/GitHub/HDMI_project/HDMI/HDMI_Main/HDMI_Main.srcs/sources_1/bd/block_diagram_HDMI/ip/block_diagram_HDMI_clk_wiz_0_0/block_diagram_HDMI_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_diagram_HDMI_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/vsoab/Documents/GitHub/HDMI_project/HDMI/HDMI_Main/HDMI_Main.srcs/sources_1/bd/block_diagram_HDMI/ip/block_diagram_HDMI_clk_wiz_0_0/block_diagram_HDMI_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_diagram_HDMI_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/vsoab/Documents/GitHub/HDMI_project/HDMI/HDMI_Main/HDMI_Main.srcs/sources_1/bd/block_diagram_HDMI/ip/block_diagram_HDMI_clk_wiz_0_0/block_diagram_HDMI_clk_wiz_0_0.xci
# IP: The module: 'block_diagram_HDMI_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vsoab/Documents/GitHub/HDMI_project/HDMI/HDMI_Main/HDMI_Main.srcs/sources_1/bd/block_diagram_HDMI/ip/block_diagram_HDMI_clk_wiz_0_0/block_diagram_HDMI_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_diagram_HDMI_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/vsoab/Documents/GitHub/HDMI_project/HDMI/HDMI_Main/HDMI_Main.srcs/sources_1/bd/block_diagram_HDMI/ip/block_diagram_HDMI_clk_wiz_0_0/block_diagram_HDMI_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_diagram_HDMI_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/vsoab/Documents/GitHub/HDMI_project/HDMI/HDMI_Main/HDMI_Main.srcs/sources_1/bd/block_diagram_HDMI/ip/block_diagram_HDMI_clk_wiz_0_0/block_diagram_HDMI_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_diagram_HDMI_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
